version: '3'

services:
  linksdb:
    image: postgres
    container_name: linksdb
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=linksdb
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
